### ISSUE TITLE
input are not controlled by `value`

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#394] opened 2021-04-08 14:11 UTC
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**

I passed a string as value into `<input/>`. when user type, I didn't change the value, but the value in the input element are still changed.

**To Reproduce**

see [playground](https://playground.solidjs.com/#NobwRAlgJmBcYA4BWBHAhgJgG4HsIE4AWABgCcAbAVwHNLKAXATygFMwAaMAOzQFs34vNBC4cwTAA4DxAZwAeYmTkqkAxtIi8JOUvQAEIPaRZdWpPQF89AM1I5eegORLy0ALRIZAegDuLAEaOANwAOlxh1pRcqvQQOFx6AMLKXPQspAAUAJQGYXp6qvEy+lhoVCx6ALxO1hByLFDBYXlGLPQqCRkt+QA8IhIMeqXllSDDlCxW8QCSXAP0oxWVAHwFRTjkLAB05DjUGdv0aKTUbVvjLFkWXsstWaFcFs1cxqbpGdlVqz3JUWnmN3YeigOFUlH4qS2p3oAFFNhD6AAhRjTKAZRxoCQSRxZLJhMAWAC6QA)

**Expected behavior**

if I do not change the value, the value in element should not change. (as what is in react)

**Comment by ryansolid** [comment] 2021-04-08 16:34
Yeah this one is pain. React does something special here. I'm not sure who else does. The problem is you need to hack the input to actually maintain this. And add a bunch of other even listeners. I don't think this is something that I intend to ever implement. Someone did an audit a while back and realized only React was doing this out of all the libraries they tested. I don't see us keeping natural DOM behavior and implementing this.

I'm pretty much a won't fix on this. But if there is overwhelming support in other libraries like Preact, Inferno, and Svelte I might consider it (but if memory serves none of these outside of compat do this).

**Comment by thefliik** [comment] 2021-04-13 08:46
FWIW, my background is mainly in Angular but I find the current functionality expected. In fact, I'd be _very surprised_ if the input value didn't update. From this conversation, I gather that, in React, the input wouldn't update. But if react is re-rendering the function component on every keypress I could see this making sense (as it is effectively re-initializing the input with a static value on every keypress). But the current behavior of Solidjs seems consistent with the DOM itself (e.g. if you create an `<input value="fixed" />` you'll find that you can still change the input's value) and is what I would expect to happen.

**Comment by ryansolid** [comment] 2021-04-21 09:18
I'm going to move this to discussions as no activity for 2 weeks and I don't see implementing this.

**Closed** 2021-04-21 09:19 UTC
Labels: wontfix
