### ISSUE TITLE
Select Options Corner Case

### ISSUE THREAD

**Issue by rturnq** [ryansolid/solid#158] opened 2020-05-14 19:46 UTC
There seems to be an issue around maintaining the selected value for a `select` element when replacing its options. In some situations:

- When the options are rendered from an array and the array elements are objects
- And the array is replaced (even with equivalent items)

The select element's selected option reverts to the first options and its `selectedIndex` === 0.

Interestingly, if the elements of the array driving the options are primitives, the selected option is maintained unless that option is removed - as expected.

Here is an example which illustrates the issue: https://codesandbox.io/s/solidselect-options-ldv2u

**Comment by ryansolid** [comment] 2020-05-14 20:58
It's because it is no longer referentially equal after you do the mapping. So the behavior is expected. Think Redux or immutable data here. When you append to a list you don't create everything on map again. You do a lookup against previous state and return the same thing unless it's new or changed.

There are a couple options. I am assuming you are not using primitives for a reason. Since that also solves this problem. Traditionally in these sort of libraries you'd use the the reactive map function `mapArray` which is the underpinnings of `<For />`:
```js
const options = mapArray(() =>
  state.input
    .split(",")
    .map(value => value.trim())
    .filter(value => !!value)
  , value => ({ value, label: value })
);
```
This is just making it about the primitive value again and only creating new objects when the value doesn't exist in the list otherwise it reuses the previous iteration. Useful for keeping references to nested reactive data.

Mechanically it is doing a lot more than all that is needed here. If you prefer the approach more similar to immutable data and just use a normalized object:
```js
 const items = {}
 const options = () =>
    state.input
      .split(",")
      .map(value => value.trim())
      .filter(value => !!value)
      .map(value => {
        if (value in items) return items[value];
        return items[value] = { value, label: value }
      });
```
Either these depending on your situation I hope are reasonable solutions.

**Comment by rturnq** [comment] 2020-05-14 22:26
Ok, I think I understand. Ultimately the `option` element for the current value is removed and replaced which causes the DOM to set the selected index to 0. I'm not super keen on babysitting the options array. In the real world this may be coming from some external source like an API and having to make sure you never replace an object seems like a pain.

I think maybe the underlying issue is keeping the state of the `select` in sync with with the application state. In that example, when the options are replaced, and the selected index changes to 0, the state is never notified and updated - the DOM doesn't fire the onchange event in this case. Because the state is now out of sync it becomes impossible to programatically set it back to the desired value without getting a reference to the actual element or setting the value twice.

Probably what I will do is wrap the select and codify the options as a prop and keep a ref to the select element. Then I can tack changes to the options and value and ensure everything is kept in sync. This is in line with a similar problem keeping a text input value in sync if you want to limit the characters a user can enter. 

The reason for not using primitives is there is often additional information that needs to be provided to the option: the label may differ from the value, you might want to control the disabled state, etc. Its just simpler to wrap it all up in an object that describes the option.

**Comment by ryansolid** [comment] 2020-05-14 22:49
I mean the third option if you are talking data snapshots coming form an API is store the list in state and use `reconcile`. Admittedly I haven't ever worked in cases where I was updating on data snapshots like that for things like dropdown, but that's what it is there for. Typically I'm used to loading in whole models and replacing parts of the page and doing finer grained updates. But given your source was just primitives I offered those up.

Select in general do have that problem. I've hit this in KnockoutJS before too. It also matters the order of them being set.. Like if you select before the list has loaded etc.. Order matters etc.. With the character limit issue you can handle most of it in the `input` event. But I guess this is different because it updates without end user action.

**Comment by rturnq** [comment] 2020-05-15 00:27
So I wrote a little wrapper around select

```jsx
function Select(props) {
  const { options, onChangeValue, ...rest } = props;
  let elementRef; 

  createEffect(() => {
    const index = props.options.findIndex((option) => option.value === props.value);
    if (index > 0) {
      // Wait for the select's options to be replaced before checking anything
      requestAnimationFrame(() => {
        if (elementRef && elementRef.value !== props.value) {
          elementRef.selectedIndex = index;
        }
      });
    } else if (props.onValueChange && props.options.length) {
      const option = props.options[0];
      props.onValueChange(option.value, 0, option);
    }
  });

  function handleChange(evt) {
    const { selectedIndex } = evt.target;
    const option = props.options[selectedIndex];
    props.onValueChange &&
      props.onValueChange(option.value, selectedIndex, option);
    props.onChange && props.onChange(evt);
  }

  return (
    <select {...rest} ref={elementRef} onChange={handleChange}>
      <For each={props.options}>
        {(option) => (
          <option value={option.value}>{option.label ?? option.value}</option>
        )}
      </For>
    </select>
  );
}
```

It requires you define your options as an array of `{ value, label }` objects which I kinda like and adds a new `onValueChange` event which is notified if the user selects a new value or the options change. Seems to work well but I am relying on `requestAnimationFrame` to wait for the select's options to get replaced so the `selectedIndex` can be "fixed" if needed. Relying on timing like this always feels bad, is there a more idiomatic way? Also, I don't think extracting the original select props using a rest/spread works in the way I think.

**Comment by ryansolid** [comment] 2020-05-15 02:44
Yeah I mean you might not need to wait til the next animation frame. But that is all any library does. `useEffect` in React executes after a batched update cycle basically scheduled more or less the same way. And you are right about the spread. It won't ever update. The problem is the clone will have the values but not the dynamic getters. I actually had a good conversation today that suggested that we need a `splitProps` operator to let us keep things reactive. I think it would work for splitting state too.

I just want to come up with a good API for it. My first thought is:
```js
function splitProps<T>(props: T, ...[[ key of T ]]): Partial<T>[]

// like:
const [myProps, rest] = splitProps(props, ["options", "onChangeValue"])
// or
const [myProps, containerProps, rest] = splitProps(props, ["options", "onChangeValue"], ["headerClass"])

// then you access like
myProps.options
//or
<div {...rest} />
```
It was also suggested to pass an object instead of an array to set default values. We do already have a method for that with `defaultProps` but it's worth consideration.

**Comment by ryansolid** [comment] 2020-05-17 00:37
I actually implemented `splitProps`. I think this is an important use case that I sort of glazed over, given my bias against spreads. https://github.com/ryansolid/solid/blob/master/packages/solid/src/rendering/component.ts#L46

It will be in the next release of Solid.

Is there anything else I can help with? I think selects are one of those fiddly elements, I'm not sure there is much else I can do here. Knockout used have custom bindings just for select lists, but I believe I could still hit issues like this when setting a value, and then making the list shorter.

**Comment by rturnq** [comment] 2020-05-18 18:23
I tried a few things and using `requestAnimationFrame` seems to have the best results. Doing nothing means the select still has it's _old_ options at the time the effect runs and using `setTimeout` causes the default option to show for a few milliseconds before the correct selection is made. I'll stick with that for now.

`splitProps` looks pretty good, though I think there is room for improvements on the typings so you don't just get a bunch of `Partail<T>`s as a result. I haven't figured out a more elegant solution but the following could be a starting point:

```ts
export function splitProps<T extends object, K1 extends keyof T>(props: T, ...keys: [K1[]]): [Pick<T, K1>, Omit<T, K1>];
export function splitProps<T extends object, K1 extends keyof T, K2 extends keyof T>(props: T, ...keys: [K1[],K2[]]): [Pick<T, K1>, Pick<T, K2>, Omit<T, K1 & K2>];
export function splitProps<T extends object, K1 extends keyof T, K2 extends keyof T, K3 extends keyof T>(props: T, ...keys: [K1[],K2[],K3[]]): [Pick<T, K1>, Pick<T, K2>, Pick<T, K3>, Omit<T, K1 & K2 & K3>];
export function splitProps<T extends object, K1 extends keyof T, K2 extends keyof T, K3 extends keyof T, K4 extends keyof T>(props: T, ...keys: [K1[],K2[],K3[],K4[]]): [Pick<T, K1>, Pick<T, K2>, Pick<T, K3>, Pick<T, K4>, Omit<T, K1 & K2 & K3 & K4>];
export function splitProps<T extends object, K1 extends keyof T, K2 extends keyof T, K3 extends keyof T, K4 extends keyof T, K5 extends keyof T>(props: T, ...keys: [K1[],K2[],K3[],K4[],K5[]]): [Pick<T, K1>, Pick<T, K2>, Pick<T, K3>, Pick<T, K4>, Pick<T, K5>, Omit<T, K1 & K2 & K3 & K4 & K5>];
export function splitProps<T>(props: T, ...keys: [(keyof T)[]]) {
  // existing implementation
}
```

It might be nice to use an object and incorporate the default props behavior in this function making it a one-stop solution for managing props. `setDefaults` doesn't really work great in TypeScript since you're stuck with the original props type. Doing it here would give you a chance to change the type for better ergonomics:

```ts
interface Props {
  foo?: number
  bar?: string
}

const [{ myProps, otherProps }, rest] = wrangleProps(props, {
  myProps: {
    foo: 1
  },
  otherProps: {
   bar: 'acb'
  }
});

// typeof props.foo == number | undefined
// typeof myProps.foo == number
```

That being said, I don't tend to use default props in Solid or React but usually push the default resolution into utility function parameters or maybe a memo.

Feel free to close this issue at your convenience.

**Comment by ryansolid** [comment] 2020-05-18 18:41
Well I'm glad I left this around long enough to get some tips on the TypeScript.  I wasn't aware of pick/omit but I think that is plenty fine for a pretty shallow depth.. Like how many splits are we going to do. I'm going to leave the object out for now since I have the other function. We will see if it makes sense in the future. Thanks for your feedback.

**Closed by ryansolid** 2020-05-18 18:41 UTC
Labels: question
