### ISSUE TITLE
Solid + Shoelace css + onClick = Tab completely freezes

### ISSUE THREAD

**Issue by doronnac** [ryansolid/solid#246] opened 2020-10-24 08:03 UTC
Added a repo
https://github.com/doronnac/solid-repro

If you click on the hamburger icon, the app completely freezes without any error.
This stops happening when you comment `defineCustomElements()` which is in `index.tsx`
Note the web component will still work as intended thanks to CDN download in `index.html`.

Also this seems to be caused only when using `<sl-icon-button>` element, which requires additional setup (`index.html`, lines 36, 38-42)

- `defineCustomElements()` will _not_ cause a freeze if you remove the div's `onClick` handler
- `defineCustomElements()` will _not_ cause a freeze if you replace the div's `onClick` with a `on={{click: () => {}}}` handler

Sorry in advance if this issue belongs in `dom-expressions` monorepo, was already created, or is not caused by Solid.

Thank you

**Comment by ryansolid** [comment] 2020-10-24 20:15
I will try your reproduction tonight. Thanks for reporting.

**Comment by ryansolid** [comment] 2020-10-25 03:29
This is pretty weird issue. This custom element library sets themselves as their own host creating an infinite loop. Generally speaking the host property lets you go from shadow root to element container. I use it with event delegation to traverse from shadow roots back up through the light DOm up to the document. I also use this mechanism for Portals to indicate the intended parent traversal. 

However, ShoelaceCSS seems to also set the custom elements host to itself which breaks my traversal as it's an infinite loop. Strange thing to do since it would break any upward traversal. Useful for things like context traversal and I use this mechanism ina number of my libraries.

As you've noticed not using Solid's event delegation works or for some reason not registering the custom element. I'm unclear why it would still be working or working differently under the different initialization but it is not setting the custom elements host in that case.

I suppose you could just turn off all event delegation by passing `delegateEvents: false` to `babel-preset-solid`. It is a performance deopt but not a major one. I can look at breaking the loop but unfeasible to do more than a single depth check.

**Comment by ryansolid** [comment] 2020-10-25 07:07
Fixed in 0.21.2.

**Closed by ryansolid** 2020-10-25 07:07 UTC
