### ISSUE TITLE
Trying to get styled-system working

### ISSUE THREAD

**Issue by praneybehl** [ryansolid/solid#148] opened 2020-04-26 12:14 UTC
Trying to get styled-system to work with solid-styled-system(goober) but it seem to be not working:
https://codesandbox.io/s/solid-goober-styled-system-emiq6?file=/index.js

Although, trying with emotion works:
https://codesandbox.io/s/solid-emotion-py2hy?file=/index.js

Any idea why?

**Comment by ryansolid** [comment] 2020-04-27 00:44
Looks like Goober isn't serializing the object passed that way and just setting it to "object". I know it supports top-level object functions. I want to verify it with a different library with Goober like preact and they are in the process of winding up for 2.0.0 release. But I will look at opening up an issue on Goobers repo.

**Comment by ryansolid** [comment] 2020-04-27 02:44
Ok confirmed this is functionality they do not have currently. While you can pass in object form top level it currently isn't supported nested in templates. I've opened up an issue. https://github.com/cristianbote/goober/issues/136

**Comment by cristianbote** [comment] 2020-10-20 08:56
Hey there, pushed a new version `2.0.9` which now interpolates/compiles the objects inside the tagged templates as well. Hopefully this will get it going 👍  if not please let me know so I can address it.

**Comment by praneybehl** [comment] 2020-10-20 09:44
Hi @cristianbote, thank you for the update.
@ryansolid can we please bump the goober version on the solid-styled-components package?

**Comment by ryansolid** [comment] 2020-10-20 15:53
Sure no problem I can do that tonight.

**Comment by ryansolid** [comment] 2020-10-21 09:38
So happy to close this one. v0.21.1. Enjoy.

Thanks @cristianbote.

**Closed by ryansolid** 2020-10-21 09:38 UTC
Labels: enhancement
