### ISSUE TITLE
Named component exports

### ISSUE THREAD

**Issue by KyivJunta** [ryansolid/solid#141] opened 2020-04-15 12:58 UTC
Hey, great library! I was playing with default js template and stuck with strange behavior: when I use named component exports, e.g.:
```jsx
export function App() {...}
```
on import, I am always getting an error:
```Attempted import error: 'App' is not exported from './components/App'.```

Also, barrel exports do not work with either named export, nor default export.

Am I doing something wrong here or library/tooling has some limitations?

**Comment by ricochet1k** [comment] 2020-04-15 13:31
Works for me using Parcel 2. Also works here: https://codesandbox.io/s/solid-counter-ngikg?file=/index.js

**Comment by KyivJunta** [comment] 2020-04-15 13:43
The thing is, that `npm init solid app app_name` from the "Get started" section uses `create-solid` package, which by itself adapted from `create-react-app` and uses `solid-scripts` with `webpack` underneath.
ATM I don't know if there something wrong with `create-solid` or `solid-scripts` or something wrong with solid tooling underneath.
As workaround, I can use Parcel 2, but where the thing is broken in unknown.

**Comment by ryansolid** [comment] 2020-04-15 14:29
It's due to solid-hot-loader. It requires default export to find the Component to reload. I'm not sure how I'd make this opt in. Its caused enough confusion I'm debating just removing it. The challenge with it is given how Solid works it needs to be applied to each Component not just at the root so it needs to work via Webpack rule. I suppose I could impose a custom extension like `.hot.js` but maybe that's weird.

**Comment by KyivJunta** [comment] 2020-04-15 15:34
`hot` infix is definitely is not an option - we should not force naming rules/conventions for tooling purposes. As an option, hot-reloading behavior can be guarded by flag, but optimal solution would be to opt out hot-loading entirely for now.

**Comment by KyivJunta** [comment] 2020-04-15 15:35
Also, os there plans to fix current CLI behavior?

**Comment by ryansolid** [comment] 2020-04-15 15:45
Yeah the problem is to a degree has to be a convention, because you still can't match against every file in a project. Currently I use the component folder as a rule. Using an extension atleast removes that constraint. But I'm onboard removing this for now. It's not that useful.

@KyivJunta Are you asking if I intend to remove it for now or are different CLI behaviors you are referring to?

**Comment by ryansolid** [comment] 2020-04-15 16:10
Ok this should be fixed with solid-scripts v0.0.31. Thanks for bringing this to my attention and forcing the decision. Sometimes we have seemingly good ideas but sometimes the challenge of generalizing them makes it unsuitable for the lowest common denominator.

**Closed by ryansolid** 2020-04-15 16:10 UTC
