### ISSUE TITLE
JSX compiler bug?

### ISSUE THREAD

**Issue by kenfoo** [ryansolid/solid#82] opened 2019-09-30 18:50 UTC
This sample code will fail to run. I'm getting the runtime error:
Uncaught ReferenceError: _ret is not defined

```js
import {  render } from 'solid-js/dom';

function MyComp() {
  let children: HTMLElement[] = [];
    for (let c = 0; c < 7; c++) {
      const content = "test";
      if (c==0) {
        children.push(<span>{content}</span>);
      } else {
        children.push(<span>{content}</span>);
      }
    }
  return <div>{children}</div>
}

render(MyComp, document.body);
```

**Comment by atfzl** [comment] 2019-09-30 18:59
The compiled output of this code is:

```js
import { template as _$template } from "dom";
import { insert as _$insert } from "dom";

const _tmpl$ = _$template(`<span></span>`),
      _tmpl$2 = _$template(`<div></div>`);

import { render } from 'solid-js/dom';

function MyComp() {
  let children = [];

  for (let c = 0; c < 7; c++) {
    const content = "test";

    if (c == 0) {
      children.push(function () {
        var _ret;

        const _el$ = _tmpl$.content.firstChild.cloneNode(true);

        _$insert(_el$, content);

        _ret = _el$;
        return _ret;
      }());
    } else {
      children.push(function () {
        const _el$2 = _tmpl$.content.firstChild.cloneNode(true);

        _$insert(_el$2, content);

        _ret = _el$2;
      }());
    }
  }

  return function () {
    const _el$3 = _tmpl$2.content.firstChild.cloneNode(true);

    _$insert(_el$3, children);

    return _el$3;
  }();
}

render(MyComp, document.body);
```

@ryansolid looks like the `_ret` variable is declared in `if` block and is not available in `else` block.

**Comment by ryansolid** [comment] 2019-09-30 19:13
Yeah this is super weird. Something Babel is automatically doing for some reason. The _el$3 block is the babel code I generate. Using the temporary return variable there is something they are doing to handle that code block. I might be able to wrap the function execution myself but I have no idea why they are injecting _ret. I haven't had any luck finding any existing babel pugs yet.

**Comment by ryansolid** [comment] 2019-10-01 04:34
Ok looks like a super small change to the Babel output fixes it. Apparently, the way I was doing the replacement statement left things open for interpretation that caused different code generation when inside a for loop.  I've addressed this in the latest version of Babel JSX DOM Expressions Plugin (v0.12.1) as used by Babel Preset Solid. Thanks for reporting.

**Comment by trusktr** [comment] 2019-10-02 17:45
> different code generation when inside a for loop

Seems like a bug that should be reported to Babel?

**Comment by ryansolid** [comment] 2019-10-02 18:17
Yeah I am not clear what the expected behaviour is for Babel, but this does seem like it has to be wrong. Basically on the path object they have a replaceWithMultiple which can be multiple statements replacing a single one. They auto wrap this in a iife (aware of wrapped closures etc, like this etc...). Initially my last statement was just a generic statement with the identifier expression (the one I'd return). I changed it to a return statement and it fixed the problem. So in a sense I can say what I was doing was wrong. But I suppose I can also say that the code they generate is wrong too if a conditional in the iife causes variables to used out of scope.

**Closed** 2019-10-03 04:27 UTC
Labels: bug
