### ISSUE TITLE
sass/scss support?

### ISSUE THREAD

**Issue by btakita** [ryansolid/solid#122] opened 2020-02-21 04:22 UTC
Hello, has anybody integrated sass/scss with Solid? Are there any examples out there?

**Comment by ryansolid** [comment] 2020-02-21 04:54
Do you mean like using it via Webpack? Using CSS preprocessing comes down to the bundler. Create Solid (`npm init solid app my-app`) uses sass but that is sort of buried. But in terms of a basic config it should work the same as you would with React.

Webpack Loader: https://webpack.js.org/loaders/sass-loader/
Or using post-css: https://github.com/postcss/postcss-loader

Rollup: https://github.com/egoist/rollup-plugin-postcss

I think Parcel might be the easiest: https://parceljs.org/scss.html

I just did a quick browse through projects using Solid and I didn't see any current projects using sass in the config. So if anyone else knows of one feel free to share.

Otherwise @btakita if you have a bundler of choice I can probably help. I've setup webpack and rollup to handles sass in the past.

**Comment by praneybehl** [comment] 2020-02-26 01:38
@btakita I added SCSS styles to the counter example as quick POC:
https://codesandbox.io/s/scss-solid-counter-nr6we

@ryansolid also created a PR to add the sample in the README https://github.com/ryansolid/solid/pull/123

**Comment by ryansolid** [comment] 2020-02-26 03:40
@praneybehl thanks. I was debating doing something like that but I was thinking the issue here was more fundamental with bundler as setting this stuff up once you've done it before is the same no matter what framework you use. Parcel is by far the simplest as you basically don't need to do anything.

I think the real issue here is just not having enough full from nothing to app tutorials for Solid specifically. One that goes through making the webpack build etc.. However, projects like Create Solid App has made starter templates less common these days. On one hand, I can shelve that and point to Create Solid App, but I think that isn't where people necessarily start from if their goal is to grow. The problem being it isn't one size fits all, so it's a lot easier for me to answer specific questions than go through all the permutations. 

In any case this is an example. @btakita where you looking for an example with a specific bundler?

**Comment by praneybehl** [comment] 2020-02-26 05:22
@ryansolid I totally agree with you that the issue is more fundamental to the bundler. My point of throwing the quick sample was to show that not matter which bundler you use, there is no extra settings/magic needed for SCSS to work with Solid. Most of the setups can just be brought in from react/jsx world and most likely they would work. 

Disclaimer, no react dependant libraries/package would work just out of the box with Solid though.

**Comment by ryansolid** [comment] 2020-02-29 06:50
Since there's been no new activity and this isn't directly part of this library. I'm going to close this.

**Closed by ryansolid** 2020-02-29 06:50 UTC
Labels: question
