### ISSUE TITLE
Import Components and Dot Notation 

### ISSUE THREAD

**Issue by rturnq** [ryansolid/solid#133] opened 2020-03-26 21:23 UTC
I've run into an issue importing objects which contain components and subsequently rendering those components using JSX and dot notation (eg. `<MyComponents.Foo />`). If `MyComponents` is being imported from another file, this will fail with an error `MyComponents is not defined`. If `MyComponents` is a variable within that file, everything works fine. Note this only presents as a runtime error, TypeScript is perfectly happy with it.

[Here](https://codesandbox.io/s/component-import-issue-nlvw7) is an example of the issue, some things that work and some that do not.

Normally this is not a problem, I generally only include a single component per file and import them individually. The place this came up was exporting a context object created with `createContext` and then trying the render the `Provider` component from that context object.

Ultimately this can be worked around fairly easily by exporting and importing the components directly or assigning them to local variables. I wanted to bring this up because it took me a little while to identify why my code was breaking and it could be a gotcha for others. It should also be noted that this type of thing works in React and they address it in their [docs](https://codesandbox.io/s/component-import-issue-nlvw7). I certainly don't expect Solid to work exactly like React, but since the context API is very similar to React's it is an easy trap to fall into.

**Comment by ryansolid** [comment] 2020-03-26 23:05
Hey thanks for reporting. Looking at this example I'm a little confused. I'm going to dig in a bit but generally Solid supports namespaced components ie.. `MyContext.Provider` and it only transforms the JSX so if symbols are missing from the top of the file that's an issue with how the code is written or some transformation being done with the bundler, in this case Parcel, and has nothing to do with the UI library, Solid. I will look a little bit closer but I suspect that the default config for Parcel in CodeSandbox is coercing to CJS and that's messing with the way it's handling the default import for some reason. In any case I'm a bit curious to see what's going on so I'm going to take a look.

**Comment by ryansolid** [comment] 2020-03-26 23:28
Ok I see the issue. It's a weird one. Basically when they mutate for commonjs it isn't picking up those symbols. I think I know the cause https://github.com/ryansolid/babel-plugin-jsx-dom-expressions/pull/28. When the code was refactored it switched to string concatenation which works in ES6 environments. But for some reason it messes with the transpiler's ability to pick up the symbols when changing module systems. Luckily nothing serious just weird Babel issue that managed to sneak under all the tests as we don't run the tests through preset-env.

**Comment by ryansolid** [comment] 2020-03-27 00:27
Ok fixed in babel-plugin-jsx-dom-expressions v0.17.1. Technically babel-preset-solid will support that but need to blow away any package locks. (And there was one code bug where I had to import as *) but I think we are good. See it here: https://codesandbox.io/s/component-import-issue-9oc59

**Closed** 2020-03-27 14:43 UTC
Labels: bug
