### ISSUE TITLE
solid element not works as expected

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#276] opened 2020-12-06 16:55 UTC
I've create something to have a try with solid element

```
// App.tsx

import { createEffect, createSignal, onCleanup, onMount, Show } from 'solid-js';

export const App = () => {
  const [showTimer, setShowTimer] = createSignal(true);
  const [count, setCount] = createSignal(0);
  const timer = setInterval(() => setCount(count() + 1), 1000);

  onCleanup(() => {
    clearInterval(timer);
  });

  return (
    <>
      <div>
        <button onClick={() => setShowTimer(!showTimer())}>toggle</button>
        <Status show={showTimer()} />
        <Show when={showTimer()}>
          <Timer count={count()} />
        </Show>
      </div>
    </>
  );
};

const Timer = (props: { count: number }) => {
  onMount(() => {
    console.log('mount timer');
  });

  onCleanup(() => {
    console.log('clean timer');
  });

  createEffect(() => {
    console.log('...', props.count);
  });

  return (
    <div>
      <span>{props.count}</span>
    </div>
  );
};

const Status = (props: { show: boolean }) => {
  return <p>show: {String(props.show)}</p>;
};

```

```
// index.tsx

import 'solid-styled-jsx';
import { customElement } from 'solid-element';
import { App } from './App';

customElement('my-app', { name: 'XXX' }, (props, { element }) => {
  return (
    <div>
      <p>hello {props.name}</p>
      <App />
    </div>
  );
});

```

But there are something not as expected

- the custom element props are not reactive, that is, when I update the prop name of `my-app` in the chrome devTool, the rendered text did not change
- the onMount of `Timer` component is not triggered, but when I toggle it shown or hidden, the onMount and onCleanup got triggred.
- the onCleanup of `Timer` was not triggered when I delete the `my-app` element in the chrome devTool
- [solid-styled-jsx](https://github.com/ryansolid/solid/tree/master/packages/solid-styled-jsx) didn't work when the component is under solid element

**Comment by ryansolid** [comment] 2020-12-07 03:47
Hmm.. copy and pasted the code.  https://codesandbox.io/s/reproduction-276-hiq85?file=/index.tsx

I wasn't able to reproduce the issues. I using the chrome dev tools to get a reference $0. Setting the name by both property(`$0.name = "HHH"`) and attribute(`$0.setAttribute("name", "TTTTT")`) updated. The onMount trigger seems to work initially and cleanup when I removed it (`$0.remove()`).

As for solid-styled-jsx I wonder if it simply because of the Shadow DOM getting in the way. Mind you with Solid you don't need solid-styled-jsx. You have the Shadow DOM which automatically scopes styles. Styled JSX is basically a poor imitation for the Shadow DOM for when you aren't using Web Components. You shouldn't need anything special on the CSS side here. Just write a style tag in your component and it will be scoped.

**Comment by zhaoyao91** [comment] 2020-12-07 06:39
@ryansolid strange, it seems work in your codesandbox. I've pushed a demo project here: https://github.com/zhaoyao91/solid-element-demo you can run `npm run dev` to see the effect(reactive not working)

**Comment by ryansolid** [comment] 2020-12-07 08:48
You have 2 versions of Solid in your package. It is getting bundled twice since your versions of solid-js and solid-element don't match and its installing 2 versions. This duplication of instances is why its not reactive. Easiest way to fix it is remove `solid-js` from the package.json and `solid-element` will pull the right version in.

**Comment by zhaoyao91** [comment] 2020-12-07 09:07
@ryansolid sadly it seems not working by just removing `solid-js`. project cannot resolve correctly. Maybe `solid-element` should delare solid-js as peerDependencies instead of dependency

**Comment by ryansolid** [comment] 2020-12-07 09:19
Did you clear your package-lock and clear your node modules first? And re-install everything? I imagine your build is more than about 1100 lines, which suggests you should be able to find solid-js top level and under solid-element in your node_modules. It sounds like a duplicate is getting in somewhere. And if it isn't resolving that sounds like the top level folder was removed instead of the nested one.

I just did this before I responded and had no issues (plus it's how it works in all the demos).

I debated peer dep. Wasn't sure which way to go so just followed suit from LitElement which treats lit-html as a dependency. The reactive duplication issue might be enough reduce scenarios where it can happen.

**Comment by zhaoyao91** [comment] 2020-12-07 13:12
After remove node_modules and re-install, I got it work as the `solid-js` is now at the top level.

But, `solid-js` at the top level of node_modules is just an coincidence, not an explicit declaration of the project, it is not safe. For example, if the project is under a yarn workspace or other monorepo, the package hierarchy may be different and the resolves broken.

The fact is, the project itself and the `solid-element` both requires `solid-js`, so they all should declare `solid-js` as their deps. This lead to the two instances of solid-js problem and that's why peer deps comes in. `solid-element` is a middle level package, not the final app project, by declaring `solid-js` as its peer deps, it says `want it, but the final project should install it as we should share the same instance`.

I see the lit-element declare lit-html as deps instead of peer deps that's because the `lit-element` fully encapsulate the `lit-html` as its internal things and expose the critical things like `html` to the users directly. But `solid-element` didn't encapsulate `slid-js`, we still need to import things from solid-js. That's why I suggest peer deps over deps for solid-element.

**Comment by ryansolid** [comment] 2020-12-07 17:37
Ok sold. That's a good criteria. I can update it appropriately.

**Closed** 2020-12-08 03:52 UTC
