### ISSUE TITLE
TypeScript: Component typing

### ISSUE THREAD

**Issue by high1** [ryansolid/solid#139] opened 2020-04-13 13:22 UTC
There should be an example of typing components - @typescript/eslint shows a warning with default configuration. Is there something inside Solid type definitions - if there is, excuse my ignorance...

**Comment by ricochet1k** [comment] 2020-04-13 13:36
More detail is always appreciated in issues. What warning are you seeing? What default configuration are you talking about? How did you create it? How do you reproduce the warning?

Component and JSX related typing is all here: https://github.com/ryansolid/dom-expressions/blob/master/packages/babel-plugin-jsx-dom-expressions/types/index.d.ts

**Comment by high1** [comment] 2020-04-13 13:40
Missing return type on function.

```
const Counter = () => {
  const [state, setState] = createState({ count: 0 }),
    timer = setInterval(() => setState({ count: state.count + 1 }), 1000);
  onCleanup(() => clearInterval(timer));

  return (
    <>
      <div>{state.count}</div>
    </>
  );
};
```
Something that would by declared as FC or FunctionalComponent in React. Is there a substitute?

**Comment by ricochet1k** [comment] 2020-04-13 14:35
The return type must be assignable to JSX.Element, so you could just do `const Counter = (): JSX.Element => {`

**Comment by high1** [comment] 2020-04-13 15:29
This would work in the simplest cases, yes. How would I type a component that I want to reuse?
```
const StyledDiv: JSX.Element = () => <div>Styled Div!</div>;

return (
    <>
      <StyledDiv />
    </>
  );
```
This results in:
JSX element type 'StyledDiv' does not have any construct or call signatures.ts(2604)

**Comment by ryansolid** [comment] 2020-04-13 15:35
I've had a real hard time with TSX. JSX.Element seems weird to me for some reason. I've had to assign it but is effectively `any`. I'm unclear what the best pattern is as you can see from my comment here: https://github.com/ryansolid/solid/pull/52#issuecomment-515786192. Is JSX.Element the right approach for Components in general even when not using JSX. I know people have written TS wrappers to make TS know that `<div />` is actually `HTMLDivElement`. I am completely open to coming up with a reasonable TS approach here.

**Comment by ricochet1k** [comment] 2020-04-13 16:53
I guess I didn't add enough detail above. [TS enforces that its return type must be assignable to `JSX.Element`.](https://www.typescriptlang.org/docs/handbook/jsx.html#function-component)

```js
//                           v - notice the return type of the function
const StyledDiv = (props: {}): JSX.Element => <div>Styled Div!</div>;
```

`JSX.Element` is [defined here](https://github.com/ryansolid/dom-expressions/blob/master/packages/babel-plugin-jsx-dom-expressions/types/index.d.ts#L10) as:
```ts
    type Element =
      | Node
      | ArrayElement
      | FunctionElement
      | string
      | number
      | boolean
      | undefined
      | unknown;
```

So the return type of the function could also be any of those options if you want to be more specific.

If we want to copy React's FC, something like this should work (not tested):
```ts
type FC<Props> = (props: Props & {children?: JSX.Children}) => JSX.Element;
```

**Comment by high1** [comment] 2020-04-13 17:04
Thanks @ricochet1k , my bad there. 

Adding Props={} should account for non-generic use case, and it works for my use case.
```
type FC<Props = {}> = (props: Props & {children?: JSX.Children}) => JSX.Element;
```

Would it be a good idea to put this inside main library type definitions?

**Comment by ryansolid** [comment] 2020-04-13 17:29
I guess my only question.. is then is the expectation that everyone needs the JSX namespace regardless even if they are using HyperScript or Tagged Template Literals. Am I shipping it in the wrong location? Should it be part of DOM Expressions(rather than the babel plugin) and built into the library? Anyone know the best practice here? Like is that other PR I linked the right approach?

**Comment by high1** [comment] 2020-04-13 18:41
DOM Expressions just don't look right to me. Components are an abstraction in the solid package, right?

**Comment by ricochet1k** [comment] 2020-04-13 18:45
As I understand it, Components aren't an abstraction of solid, they are merely functions and they disappear during runtime (correct me if I'm wrong). And Solid uses DOM Expressions as the library for DOM manipulation, so that sounds like a good place for the types.

Also, I think (hope?) solid's types linking to the JSX types in DOM Expressions should be enough to get them to be used in client applications without having to add them to typeRoots.

**Comment by high1** [comment] 2020-04-13 19:37
There's no mention of components in the DOM Expressions documentation, and that's the single reason why I don't think the typings should be there. 

> Also, I think (hope?) solid's types linking to the JSX types in DOM Expressions should be enough to get them to be used in client applications without having to add them to typeRoots.

This is a great suggestion, types that just work would make this discussion irrelevant, right?

**Comment by ryansolid** [comment] 2020-04-13 20:33
> As I understand it, Components aren't an abstraction of solid, they are merely functions and they disappear during runtime (correct me if I'm wrong). And Solid uses DOM Expressions as the library for DOM manipulation, so that sounds like a good place for the types.

Ok yes you are spot on. Solid doesn't really have Components. It's JSX that does or the render runtime. So yeah DOM Expressions seems right.

> Also, I think (hope?) solid's types linking to the JSX types in DOM Expressions should be enough to get them to be used in client applications without having to add them to typeRoots.

Yeah have any idea how to do that? Right now I override the JSX namespace.. I was worried that I shouldn't just do that to everyone. I know there are limitations in TypeScript here. I think React or Preact use their own namespace along with JSX. But I have no idea how to do this generically with DOM Expressions. So far I've managed to use the same types for my libraries. I am really interested in getting TypeScript working seamlessly if that's a thing. My understanding is it mostly works so I've been fine there, but JSX has really thrown me for a loop.

**Comment by ryansolid** [comment] 2020-04-17 16:55
Obviously I can add a FC wrapper without resolving all this.
```ts
type FC<Props = {}> = (props: Props & {children?: any}) => any;
```
It looks hacky but it's essentially what I've aliased these JSX types to anyway. But I'm super interested in what we should be doing. It would be great if we knew a component returned an HTMLDivElement when it does etc.. but I don't think current TSX can do that. I am in need of a TypeScript expert. Please help.

**Comment by high1** [comment] 2020-04-17 21:28
That would work, but it's a minimal solution really - ricochet1k gave the [link](https://www.typescriptlang.org/docs/handbook/jsx.html)to the extensive guidance on how JSX typings are checked in TypeScript. I'll try to read it - I'm getting the feeling that they have adopted React's way of typing things.
```
interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```
This is React's FC base interface definition - the unneeded stuff can be removed. I'm not sure if there is a way of knowing what exactly is component returning, I'll try to look into that also. I think that JSX typings should be imported in dom-expressions and then maybe re-exported - this should make the visible inside client applications, and then additional types could be added inside dom-expressions typings.

**Comment by ryansolid** [comment] 2020-04-19 01:42
Yeah I'm doing a significant update to DOM Expressions changing the SSR and hydration approach. I will try some stuff along with the release.

**Comment by high1** [comment] 2020-04-19 11:24
I've took a look at React and Inferno typings - they both introduce their own Element concepts,
and then JSX.Element extends their type.
```
type Key = string | number;
interface SolidElement<P> {
    type: string | FC<P>;
    props: P;
    key: Key | null;
  }
interface Element extends SolidElement<unknown> { }
```
would be something along those lines, if you'd like to have generic typings for base Elements, and the abstractions under JSX.ELement would have to go inside something like SolidNode etc.

I'd rather keep things simple, and keep what was already suggested:
```
 type PropsWithChildren<P> = P & { children?: JSX.Children };
 type FC<P = {}> = (props: PropsWithChildren<P>) => JSX.Element | null
```
this would only need JSX namespace to be visible...

**Comment by ryansolid** [comment] 2020-04-19 16:37
I'm pretty sure that type represents a VDOM node or atleast it looks like the interface for a HyperScript function. I guess the interesting question is should I be making a SolidElement so I can reference it in the libraries without including the JSX types and extending the same way. For VDOM which has to deal with VDOM nodes it's the only option.  I could accomplish this simply with DOM Expressions essentially exposing a DXElement type that the JSX types extend. Then Solid could use that type.

I've hesitated including the JSX types directly out if fear of namespace collisions. Does anyone know if there are better patterns? I have no idea of for example you can have Preact types working with React libraries through Preact Compat. Wouldn't the JSX types get confused?

**Comment by high1** [comment] 2020-04-19 20:47
Hm, I guess that really makes sense - I never thought that they would go through the effort of typing their internals in TypeScript - I had the impression that Flow is used for type checking.
Preact does this differently - it exports JSXInternals namespace from their [jsx typings](https://github.com/preactjs/preact/blob/master/src/jsx.d.ts), and then they import it in [main typings](https://github.com/preactjs/preact/blob/master/src/index.d.ts)
```
import { JSXInternal } from './jsx';
```
and then re-export that as JSX.
```
export import JSX = JSXInternal;
```
Could that be the way to avoid the global namespace collision?

**Comment by ryansolid** [comment] 2020-04-25 22:29
I've done work with DOM Expressions to actually use babel to rewrite JS files instead of using EJS templating. This makes it much easier to just require files and types in. The thing that I want to avoid is people needing to install DOM Expressions to get the JSX types since Solid's rollup output just absorbs it.  But I don't think types work that way. That's why I put it in the Babel plugin since I knew they would have it installed. I'm thinking if I copy the JSX file into the Solid project as part of the build process is really the only way to achieve this. But then I guess I could do something similar to Preact or Inferno. Global is easy because I know it would work. I'm not sure how solid-js.JSX would work as you don't need to import it in a given file. I have no idea how TypeScript knows where to get the JSX types from if not global. Is the JSXFactory the thing as suggested?

**Comment by high1** [comment] 2020-04-25 22:32
Yep, that's the way preact does it - sets h for jsxFactory in tsconfig, and the types are inferred from their JSXInternals. I don't think you should be concerned with the global export, though.

**Comment by ryansolid** [comment] 2020-04-25 23:32
Yeah and I think it also works because the end user imports h in every file. Where we don't do that here.

**Comment by high1** [comment] 2020-04-25 23:38
As I see it, there would have to be some bogus JSXFactory exported from solid, just to satisfy typings. Bogus because TSC is not used, and this would be there just to satisfy the typings. I wouldn't like that at all.

**Comment by ryansolid** [comment] 2020-05-02 06:21
Huge TypeScript improvements in v0.18.0. No longer need to specify typeroots. Also Solid now exports a `Component` type for our standard functional components.

**Closed by ryansolid** 2020-05-02 06:21 UTC
Labels: enhancement, help wanted, question
